asterisk:
  url: http://192.168.70.80:8088/
  username: risk
  password: risk
  originate-stasis: received-test
  terminate-stasis: test-dump
  end-point: SonusUK
  call-delay: 10
logging:
  level:
    com.shahbour: debug
